### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by vpmedia** [PeterHoeche/adobe-flex-pmd-plugin#1]
Hi!

Thanks for updating / publishing this!

Do you have any idea how to fix the following exception?

```
    java.lang.StringIndexOutOfBoundsException: String index out of range: -22
    at java.lang.String.substring(String.java:1954)
    at com.adobe.ac.pmd.nodes.impl.MetaDataNode.compute(MetaDataNode.java:72)
    at com.adobe.ac.pmd.nodes.impl.NodeFactory.createMetaData(NodeFactory.java:48)
    at com.adobe.ac.pmd.nodes.impl.AbstractNode.computeMetaDataList(AbstractNode.java:59)
    at com.adobe.ac.pmd.nodes.impl.VariableNode.compute(VariableNode.java:128)
    at com.adobe.ac.pmd.nodes.impl.FieldNode.compute(FieldNode.java:62)
    at com.adobe.ac.pmd.nodes.impl.ConstantNode.compute(ConstantNode.java:56)
    at com.adobe.ac.pmd.nodes.impl.ClassNode.detectConstant(ClassNode.java:397)
    at com.adobe.ac.pmd.nodes.impl.ClassNode.computeClassContent(ClassNode.java:368)
    at com.adobe.ac.pmd.nodes.impl.ClassNode.compute(ClassNode.java:129)
    at com.adobe.ac.pmd.nodes.impl.PackageNode.compute(PackageNode.java:86)
    at com.adobe.ac.pmd.nodes.impl.NodeFactory.createPackage(NodeFactory.java:57)
    at com.adobe.ac.pmd.files.FileSetUtils.computeAsts(FileSetUtils.java:134)
    at com.adobe.ac.pmd.FlexPmdViolations.computeAsts(FlexPmdViolations.java:122)
    at com.adobe.ac.pmd.FlexPmdViolations.computeViolations(FlexPmdViolations.java:101)
    at com.adobe.ac.pmd.engines.AbstractFlexPmdEngine.computeViolations(AbstractFlexPmdEngine.java:161)
    at com.adobe.ac.pmd.engines.AbstractFlexPmdEngine.executeReport(AbstractFlexPmdEngine.java:138)
    at com.adobe.ac.pmd.ant.FlexPmdAntTask.execute(FlexPmdAntTask.java:68)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

I've found [references](https://www.google.hu/search?q=flexpmd+StringIndexOutOfBoundsException&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a&channel=sb&gfe_rd=cr&ei=KGDWU7KJE-3b8gfSt4CYAg) to the issue but no solution yet..

Best Regards!

**Comment by vpmedia** [comment]
Debugging lead to the following statement which causes the issue:

```
private static const DP_DEFAULT:Vector.<Vector.<String>> = Vector.<Vector.<String>>(
        [
            Vector.<String>(["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]),
            Vector.<String>(["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"]),
            Vector.<String>(["a", "s", "d", "f", "g", "h", "j", "k", "l"]),
            Vector.<String>(["z", "x", "c", "v", "b", "n", "m", "-", "^"])
        ]);
```

So inlining Vector definitions is a no go for flexpmd.
I've solved this by moving the statement to a static initializer method ( return vector .. )

**Comment by PeterHoeche** [comment]
Thanks for figuring out the issue. Could you please provide a pull request so that the issue will be fixed.

**Comment by vpmedia** [comment]
Sorry but I don't have fix for this. I've solved the issue refactoring my ActionScript class..
I think when FlexPMD was developed there wasn't Vector support in the VM.

**Comment by vpmedia** [comment]
Btw I've mavenized your release:
https://github.com/vpmedia/mvnrepository
